FROM centos:6.8
MAINTAINER fabrefas4you

# setup
RUN yum update -y
RUN yum install -y rpm-build tar

# nginx depends
RUN yum -y install readline-devel ncurses-devel gdbm-devel glibc-devel gcc openssl-devel libyaml-devel libffi-devel zlib-devel

RUN useradd docker

# build
RUN mkdir -p /var/tmp/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
RUN chown -R docker /var/tmp/rpmbuild
WORKDIR /var/tmp/rpmbuild
ADD nginxbuild.sh /var/tmp/rpmbuild/nginxbuild.sh
ADD nginx1x.spec /var/tmp/rpmbuild/SPECS/nginx1x.spec
ADD nginx-version /var/tmp/rpmbuild/nginx-version
